### PR TITLE
Changed the TextFormField input text color

### LINKED ISSUE #61: Text written in the TextFormField in the medium_articles.dart page is not visible in the light mode
For example -

Screenshot_1611644132

### PR DESCRIPTION
**Pull request by Saransh-cpp**
As discussed, changed the color to blue. Let me know if you want any changes.

Closes #61

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@Saransh-cpp Can you make it dynamically change the text color according to the theme?

**Comment by Saransh-cpp** [comment]
Yes, working on it.

**Comment by Saransh-cpp** [comment]
@himanshusharma89 Now it changes dynamically, please review.

**Comment by himanshusharma89** [comment]
@Saransh-cpp I am pushing a major update in the repository, can you test it and then again add your changes? I suppose only a few lines are required to resolve this issue.

**Comment by Saransh-cpp** [comment]
Sure, I have never been in this situation before, do I clone your repo in my device then do the changes, push it to the forked repo and generate a PR?

**Comment by himanshusharma89** [comment]
@Saransh-cpp  For that, you need to do the following
- Add remote URL of the original repo to your forked repo: `git remote add original https://github.com/himanshusharma89/Flutter-Blog-App.git`
- Pull the update using: `git pull original master`
- Resolve the conflicts
- Do your changes, push it in your forked repo on GitHub and create PR.
- It'll auto-update this PR

**Comment by Saransh-cpp** [comment]
For some reasons this is not working,  the git pull original master shows already up to date.

**Comment by himanshusharma89** [comment]
> For some reasons this is not working, the git pull original master shows already up to date.

Can you attach screenshots?

**Comment by Saransh-cpp** [comment]
image

Here

**Comment by himanshusharma89** [comment]
> image
> 
> Here

Can you also show me the lib folder structure from your IDE

**Comment by Saransh-cpp** [comment]
image

Is it already updated?

**Comment by Saransh-cpp** [comment]
Okay yes, so I compared your repo with my local repo and they are same, so it updated somehow. So sorry for the inconvenience, I'll do the necessary changes now.

**Comment by Saransh-cpp** [comment]
Finally done, please review and let me know if you want any changes.

Edit - This was the first time I did something when the original repo was updated, so there were some weird mistakes like the first 2 commits in this PR, so sorry for that I don't know how that happened, I'll take care in the future but the last commit is what closes this issue.

**Pull request merged**
