### PR TITLE
Added all the App mockups

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Addressing #4 
Added screen mockups in the ReadMe file, hopefully this closes the issue.

### CODE REVIEW

**Comment by himanshusharma89** [comment]
Looks good to me!

**Comment by himanshusharma89** [comment]
@Saransh-cpp Which platform did you used to create the mockups?

**Comment by himanshusharma89** [comment]
@all-contributors please add @Saransh-cpp for design and doc

**Comment by Saransh-cpp** [comment]
@himanshusharma89 I used the website you provided in the issue description with the screenshots from my emulator.

**Pull request merged**
