### PR TITLE
added screen transition animation

### PR DESCRIPTION
**Pull request by AyushRajSharma**
flutter-Blog-App

### CODE REVIEW

**Comment by AyushRajSharma** [comment]
#28

**Comment by himanshusharma89** [comment]
@AyushRajSharma Resolve all the conflicts and pull the latest code.

**Review by himanshusharma89 — CHANGES_REQUESTED** [review]
- Resolve the conflicts
- The issue was about Fade transition, so don't use the leftToRight or rightToLeft

**Comment by himanshusharma89** [comment]
@AyushRajSharma Resolve the conflicts now

**Comment by AyushRajSharma** [comment]
can you tell me, how to resolve this conflict

**Comment by AyushRajSharma** [comment]
I don't know, how to resolve branch conflict , please help me!.
 what should i do for resolve this conflict.

**Comment by himanshusharma89** [comment]
@AyushRajSharma Add my repo https link as a remote and pull the master branch from it

**Comment by AyushRajSharma** [comment]
image

**Comment by himanshusharma89** [comment]
hi @AyushRajSharma, that's not how you pull the code. And the conflicts are resolved but only 2 files should be changed. I can see 18 files changed and most of those files are already added in the gtignore file. So, can you pull the lastest code again? This how you can do it:
- `git remote add upstream https://github.com/himanshusharma89/Flutter-Blog-App.git`
- `git pull upstream master`

**Comment by AyushRajSharma** [comment]
> hi @AyushRajSharma, that's not how you pull the code. And the conflicts are resolved but only 2 files should be changed. I can see 18 files changed and most of those files are already added in the gtignore file. So, can you pull the lastest code again? This how you can do it:
> 
> * `git remote add upstream https://github.com/himanshusharma89/Flutter-Blog-App.git`
> * `git pull upstream master`

image

**Comment by himanshusharma89** [comment]
@AyushRajSharma Can you do the `git config pull.rebase true` the command recommended to you in the terminal

**Comment by AyushRajSharma** [comment]
> @AyushRajSharma Can you do the `git config pull.rebase true` the command recommended to you in the terminal

nothing happend

**Comment by himanshusharma89** [comment]
@AyushRajSharma The main issue is with your git config, you have to set it for global. For e.g: 
```
$ git config --global user.name "John Doe"
$ git config --global user.email johndoe@example.com
```

**Comment by AyushRajSharma** [comment]
> @AyushRajSharma The main issue is with your git config, you have to set it for global. For e.g:
> 
> ```
> $ git config --global user.name "John Doe"
> $ git config --global user.email johndoe@example.com
> ```

already edited

**Comment by AyushRajSharma** [comment]
should i make new pr with latest repo code?

**Comment by himanshusharma89** [comment]
No @AyushRajSharma, you should not create a new PR, just try to rebase your code.

**Comment by himanshusharma89** [comment]
Any update @AyushRajSharma

**Comment by AyushRajSharma** [comment]
will do soon!!,
there is semester exam so i am little bit busy

**Comment by himanshusharma89** [comment]
Oh okay @AyushRajSharma

**Comment by himanshusharma89** [comment]
Any update? @AyushRajSharma

**Comment by himanshusharma89** [comment]
Closing this PR because of no progress.

**Pull request closed without merging**
