### PR TITLE
Medium fetch data

### PR DESCRIPTION
**Pull request by shubham-chhimpa**
added medium article fetching logic
added medium article list and fetch view
added provider package
added http package

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@shubham-chhimpa Can you attach a screenshot or a video

**Comment by himanshusharma89** [comment]
And @shubham-chhimpa also, resolve the conflicts

**Comment by himanshusharma89** [comment]
@shubham-chhimpa Attach the screenshot also

**Comment by shubham-chhimpa** [comment]
Screenshot_2020-10-06-16-38-01-047_com project blog_app

**Pull request merged**
