### PR TITLE
added Darkmode Toggle using Provider

### PR DESCRIPTION
**Pull request by arbazdiwan**
The file ./lib/models/theme_data.dart is the place to change the appearance of the app. 
Please avoid using properties like color, background-color in the widgets. 
Rather update the ./lib/models/theme_data.dart file so that the toggle-darkmode functionality works without any hassle.

### CODE REVIEW

**Review by himanshusharma89 — CHANGES_REQUESTED** [review]
I am getting this error in home.dart, `Failed assertion: boolean expression must not be null`. Fix this and I'll test it again.

**Comment by himanshusharma89** [comment]
@arbazdiwan Let me know when you update this PR

**Comment by arbazdiwan** [comment]
I have added the safety checks in ternary operators where boolean values are to be evaluated.
@himanshusharma89, Please review the commit.

**Comment by himanshusharma89** [comment]
@all-contributors please add @arbazdiwan for code

**Pull request merged**
