### PR TITLE
Implement clean navigation with generated route.

### PR DESCRIPTION
**Pull request by derangga**
Hi,
I'm trying to implement clean navigation by using `onGenerateRoute`. 
I've test the app and all the routing screens work properly.
This PR for hacktoberfest purpose :smiley:

### CODE REVIEW

**Comment by himanshusharma89** [comment]
Hi @derangga, thank you for contributing. I checked your files it is perfect. Just resolve the conflicts and I'll merge it

**Comment by derangga** [comment]
Hi @himanshusharma89 i'll be resolve the conflict. 
Should I delete unsued import ?

**Comment by himanshusharma89** [comment]
Yeah, go ahead @derangga

**Comment by himanshusharma89** [comment]
@all-contributors please add @derangga for code

**Pull request merged**
