### PR TITLE
About page updated

### PR DESCRIPTION
**Pull request by Janhavi23**
Here are the screenshots of the screen:
Aboutpage1
Aboutpage2

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@Janhavi23 Just some small changes:

- [ ] Change the app bar text to 'About'

- [ ] Slightly decrease the padding within the cards

- [ ] Add the license and contributing cards. (Use URL Launcher for launching urls)

**Comment by Janhavi23** [comment]
@himanshusharma89  Here are the screenshots:
aboutpage1
aboutpage2

**Comment by himanshusharma89** [comment]
@all-contributors please add @Janhavi23 for code, design

**Comment by himanshusharma89** [comment]
@all-contributors please add @derangga for code

**Comment by Janhavi23** [comment]
@himanshusharma89 Thank you so much!

**Pull request merged**
