### PR TITLE
Added FadeTransition using PageRouteBuilder instead of MaterialPageRoute, pushed screens/views fade in now.

### LINKED ISSUE #28: Fade Transition Between Screens

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Hopefully this closes #28 , let me know if you want any further changes in the PR. I'll try to attach some GIFs of the transitions below this comment if you want to.

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@Saransh-cpp Can you add a small gif?

**Comment by Saransh-cpp** [comment]
Sure, just give me 10-15 minutes.

**Comment by Saransh-cpp** [comment]
ezgif com-gif-maker

The animation is way smoother than it appears here ( Couldn't create a GIF with higher FPS ).

**Comment by himanshusharma89** [comment]
Perfect!

**Pull request merged**
