### PR TITLE
integrated firebase for ios

### PR DESCRIPTION
**Pull request by Dhruv-Sachdev1313**
fixes firebase integration for IOS application #34

added googleService-info.plist file under runner directory , Initialised and installed pods.
it works fine , I have added a screenshot of iOS simulator 
Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-06 at 19 48 26

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@Dhruv-Sachdev1313 Can you resolve the conflicts and is there a secret key involved in firebase integration? Because GitGuardian is showing a Google Key in public issue.

**Comment by Dhruv-Sachdev1313** [comment]
@himanshusharma89 I am still wondering that why there is a conflict. I have not changed even 1 line of code. just added the googleService-info.plist file and initialised and installed pods . that's it . and I have no idea why android/local.properties is affected. I don't think there should be a secrete key, yes I did add bundle id to the app while integrating firebase, but that should not be an issue

**Comment by himanshusharma89** [comment]
Okay @Dhruv-Sachdev1313, so try to rebase your code and push it, cause I am not getting the option to merge this PR directly

**Comment by himanshusharma89** [comment]
@Dhruv-Sachdev1313 You can add all these folders (which changes according to the environment) in .gitignore and then push it

**Comment by Dhruv-Sachdev1313** [comment]
android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
ios/Flutter/Generated.xcconfig
ios/Flutter/flutter_export_environment.sh
ios/Runner/GeneratedPluginRegistrant.m
pubspec.lock
@himanshusharma89 you mean these folders right?

**Comment by himanshusharma89** [comment]
@Dhruv-Sachdev1313 I mean all the files that change according to developers system configuration. Like local_properties change the SDK location depending upon the system.

**Comment by himanshusharma89** [comment]
@Dhruv-Sachdev1313 .gitignore is updated now, so rebase your code and push it. I'll merge it

**Comment by Dhruv-Sachdev1313** [comment]
hey @himanshusharma89 You mean I should take this .gitignore file and update it to my .gitignore(I mean that which is in my local repo go this app) and then make a PR?

**Comment by himanshusharma89** [comment]
No @Dhruv-Sachdev1313. Just pull the master branch from my repo (not your forked one). It'll rebase your code with the latest code. If you don't know how to do that, let me know.

**Comment by Dhruv-Sachdev1313** [comment]
I haven't done that before. Could you please guide me a little more. @himanshusharma89

**Comment by himanshusharma89** [comment]
@Dhruv-Sachdev1313 Add my repo clone https link https in your remote:
'git remote add random_name https_link'. After this go to the branch related to the PR, commit everything and do 'git pull random_name master'

**Comment by Dhruv-Sachdev1313** [comment]
I did exactly as you said.  the terminal shows: Automatic merge failed; fix conflicts and then commit the result. What should I do next ?@himanshusharma89 
Screenshot 2020-10-08 at 11 24 31 AM

**Comment by himanshusharma89** [comment]
@Dhruv-Sachdev1313 You have to manually resolve the conflicts, check `CONFLICT` in your terminal to find the file and update it manually. There will be a choice to save incoming changes or current changes. You can cross-check these changes from the master branch of this project.

**Comment by himanshusharma89** [comment]
Or another way is to, reset everything, pull master of my project(not your forked one) and then redo all the work for ios integration.

**Comment by Dhruv-Sachdev1313** [comment]
@himanshusharma89 Yup ,doing the second one ( doing the iOS integration again) , I couldn't resolve all the conflicts

**Comment by himanshusharma89** [comment]
@Dhruv-Sachdev1313 Make sure to pull the master

**Comment by Dhruv-Sachdev1313** [comment]
@himanshusharma89 It still did not work . While pushing my code back I am getting these warnings: 

remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File ios/Flutter/Flutter.framework/Flutter is 94.76 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB

Do you think these could be the cause of this conflict

**Comment by himanshusharma89** [comment]
There are no files bigger than 50 MB for such a push. If you like we can have a video call for this?

**Comment by himanshusharma89** [comment]
@Dhruv-Sachdev1313 Any update?

**Comment by Dhruv-Sachdev1313** [comment]
yes please! @himanshusharma89  Is there any way to push such files??

**Comment by himanshusharma89** [comment]
@Dhruv-Sachdev1313 https://meet.google.com/tnz-skpp-hvy

**Comment by himanshusharma89** [comment]
@all-contributors please add @Dhruv-Sachdev1313 for code

**Comment by himanshusharma89** [comment]
@all-contributors please add @Dhruv-Sachdev1313 for code

**Pull request merged**
