### PR TITLE
Uploading New App Logo/ App Logo Update #32

### PR DESCRIPTION
**Pull request by meetxpress**

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@meetxpress Squash the commits. Although your logo doesn't match the current UI, I'll make this PR eligible for hacktoberfest.

**Comment by himanshusharma89** [comment]
And @meetxpress don't create a PR until you are assigned for it.

**Comment by meetxpress** [comment]
Okay👍

**Comment by meetxpress** [comment]
Okay, I will keep that thing in my mind.
Actually, I have newly started contributing so I don't know how it works.

**Pull request closed without merging**
