### PR TITLE
change appbar to transparent and icon back ios

### PR DESCRIPTION
**Pull request by daruanugerah**
i have change appbar style to transparent and icon back to icon back ios in add_post.dart

### CODE REVIEW

**Review by himanshusharma89 — CHANGES_REQUESTED** [review]
There is no need for creating Stack for this, you can just do the changes in the AppBar(), revert the changes and work on AppBar() with centreTile, backgroundColor, and leading. Decrease the lines of code. Also, increase the TextFormField height for the Post Body.

**Comment by daruanugerah** [comment]
why am i used stack and safe area? because in menu bar (like signal, battery, etc) were colored deepPurple. and i must separate with stack. and in bottom of menu bar, i create container is colored background white.

but, are you want still use app bar? just change background color and use icon back with leading?

**Comment by himanshusharma89** [comment]
@daruanugerah Yeah, SafeArea is perfect, but no need for Stack and container for white background. You can set the scaffoldBackgroundColor in ThemeData in main.dart. And then you can work on App Bar. After this, you can create issues and work on them.

**Comment by daruanugerah** [comment]
okay, i have finished your requested change. i use appbar again with leading. you can check it in my other commit

**Comment by himanshusharma89** [comment]
@daruanugerah  Now you reverted everything and didn't leave the SafeArea, no increase of height in TextFormField and no modification in ThemeData. You should have read my previous comment carefully, but no issues I'll merge it. Don't just create a PR for the sake of eligibility.

**Comment by himanshusharma89** [comment]
@all-contributors please add @daruanugerah for design

**Pull request merged**
